# Generated by Django 4.0 on 2022-03-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='publicacao',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
