# Generated by Django 4.0 on 2022-03-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_publicacao_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='upload',
            field=models.FileField(upload_to='arquivos'),
        ),
    ]
