# Generated by Django 4.0 on 2022-03-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_alter_publicacao_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='url',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
