# Generated by Django 4.0 on 2022-03-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_publicacao_url_tag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='url',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
    ]
