# Generated by Django 4.0 on 2022-03-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_remove_publicacao_url_remove_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(default=1, upload_to='arquivos'),
            preserve_default=False,
        ),
    ]
