# Generated by Django 4.0 on 2022-03-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_publicacao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='imagem',
        ),
    ]
