# Generated by Django 4.0 on 2022-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_remove_publicacao_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='publicacao',
            name='upload',
        ),
    ]
