# Generated by Django 4.0 on 2022-03-13 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_remove_publicacao_descricao_remove_publicacao_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='descricao',
            field=models.TextField(default='', max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='hora',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='tag',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='paginas.tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(default=8, max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacao',
            name='upload',
            field=models.FileField(default=9, upload_to='arquivos'),
            preserve_default=False,
        ),
    ]
