# Generated by Django 4.0 on 2022-03-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0012_publicacao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='arquivos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='upload',
            field=models.FileField(blank=True, upload_to='arquivos', verbose_name='Arquivo'),
        ),
    ]
