# Generated by Django 4.0 on 2022-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_alter_publicacao_imagem_alter_publicacao_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
