# Generated by Django 4.0 on 2022-03-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0014_alter_publicacao_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='link',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
