# Generated by Django 4.0 on 2022-03-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_publicacao_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
