# Generated by Django 4.0 on 2022-03-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0016_alter_publicacao_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nomeTag',
            field=models.CharField(max_length=40, verbose_name='Tag'),
        ),
    ]
