# Generated by Django 4.0 on 2022-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0017_alter_tag_nometag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.TextField(max_length=5000, verbose_name='Descrição'),
        ),
    ]
